#!/usr/bin/env bash
#disable ipv6 on kernel
disable_ipv6() {
    if [[ -n "$(ip a|awk '/inet6/')" ]]; then
        if [[ "7" == "$(awk -F"[ |(.)?]" '{print $4}' /etc/centos-release)" ]]; then
            if ! awk '/GRUB_CMDLINE_LINUX/' /etc/default/grub|grep 'ipv6.disable=1'; then
                sed -ri 's/^(GRUB_CMDLINE_LINUX.*)(")$/\1 ipv6.disable=1\2/' /etc/default/grub
            fi
            grub2-mkconfig -o /boot/grub2/grub.cfg
        fi
    fi
}

#accelerate ssh connection
ssh_config(){
    sed -ri 's@(#?)(UseDNS yes)@\2@g' /etc/ssh/sshd_config
    sed -ri 's/^#?(Port)\s{1,}.*/\1 22992/' /etc/ssh/sshd_config
    systemctl restart sshd.service
}

#disable selinux
setSELinux() {
    [ -f /etc/sysconfig/selinux ] && { sed -i 's/^SELINUX=.*/#&/;s/^SELINUXTYPE=.*/#&/;/SELINUX=.*/a SELINUX=disabled' /etc/sysconfig/selinux; /usr/sbin/setenforce 0; }
    [ -f /etc/selinux/config ] && { sed -i 's/^SELINUX=.*/#&/;s/^SELINUXTYPE=.*/#&/;/SELINUX=.*/a SELINUX=disabled' /etc/selinux/config; /usr/sbin/setenforce 0; }
}

#disable firewalld and enable iptables
ssh_iptables() {
    sed -ri 's/^#?(Port)\s{1,}.*/\1 22992/' /etc/ssh/sshd_config
    curl -Lks4 https://raw.githubusercontent.com/coeus-lei/centos_init/master/iptables.sh|bash
    curl -Lks4 https://raw.githubusercontent.com/coeus-lei/centos_init/master/iptables_init_rules > /etc/sysconfig/iptables
    if [ $1 == "publicnet" ]; then
        sed -i '10s/$/\n-A INPUT                                  -p tcp -m tcp -m state --state NEW -m multiport --dports 22,22992 -m comment --comment "SSH_PORT" -j ACCEPT/' /etc/sysconfig/iptables
#        sed -ri '/(172.(30|25)|47.90|119.28.51.253|119.9.95.122|MOA)/d' /etc/sysconfig/iptables
    fi    
    systemctl restart iptables.service
#    systemctl enable iptables.service
    [[ "$(awk '/^UseDNS/{print $2}' /etc/ssh/sshd_config)" =~ ^[nN][oO]$ ]] || { echo 'UseDNS no' >> /etc/ssh/sshd_config && service sshd restart; }
}

#sync server's time
sync_time() {

    [ -x /usr/sbin/ntpdate ] || yum install ntpdate -y
    if grep -q ntpdate /var/spool/cron/root 2>/dev/null; then sed -i '/ntpdate/d' /var/spool/cron/root; fi
    echo -e "\n*/5 * * * * /usr/sbin/ntpdate -u pool.ntp.org >/dev/null 2>&1" >> /var/spool/cron/root
    /usr/sbin/ntpdate -u pool.ntp.org
    echo -e "\n=======\n" && cat /var/spool/cron/root
}

#upgrade yum reposition
updateYUM() {
	yum clean all && yum makecache
	#sed -i '/[main]/a exclude=kernel*' /etc/yum.conf
	yum -y install lshw vim tree bash-completion git xorg-x11-xauth xterm \
		gettext axel tmux vnstat man vixie-cron screen vixie-cron crontabs \
		wget curl iproute tar gdisk iotop iftop htop net-tools
#	. /etc/bash_completion
	[ "$release" = "6" ] && yum -y groupinstall "Development tools" "Server Platform Development"
	[ "$release" = "7" ] && yum -y groups install "Development Tools" "Server Platform Development"
}
#define new kernel configration
setSYSCTL() {
        cp /etc/sysctl.conf{,_$(date "+%Y%m%d_%H%M%S")_backup}
	curl -Lks https://raw.githubusercontent.com/coeus-lei/centos_init/master/sysctl_optimize_kernel > /etc/sysctl.conf
}

#define open-files
curl -Lks https://raw.githubusercontent.com/coeus-lei/init/master/open-files | bash
disable_ipv6
ssh_config
setSELinux
ssh_iptables
sync_time
updateYUM
setSYSCTL
systemctl stop iptables.service
